[workspace]
members = [
    "crates/*"
]
resolver = "3"

[profile.dev]
panic = "abort"
opt-level = 0       # No optimizations → fastest compile
debug = true        # Keep debug symbols
incremental = true  # Enable incremental builds
codegen-units = 256 # More parallelism in LLVM codegen (default is ~16)
lto = false         # No link-time optimization

[profile.release]
strip = false
opt-level = 3
lto = true
debug = true
# Just strip manually


[workspace.dependencies]
tun-rs = { version = "2.7.2", features = ["async_io"] }
flume = "0.11.1"
rust-tun = { path = "crates/rust-tun" }
netlink-ops = { path = "crates/netlink-ops" }
rtnetlink = { path = "crates/rtnetlink" }
rustables = { path = "crates/rustables" }
netlink-packet-audit = { path = "crates/netlink-packet-audit" }
netlink-sys = { path = "crates/netlink-sys" }
netlink-proto = { path = "crates/netlink-proto" }
tun2socks5 = { path = "crates/tun2socks5" }
socks5-impl = { path = "crates/socks5-impl" }
pidfd = { path = "crates/pidfd" }
ipstack = { path = "crates/ipstack" }
clone3 = { path = "crates/clone3" }
nsproxy-ui = { path = "crates/nsproxy-ui" }
netlink-packet-route = { path = "crates/netlink-packet-route" }
netlink-packet-utils = { path = "crates/netlink-packet-utils" }
netlink-packet-core = { path = "crates/netlink-packet-core" }
fs4 = { version = "0.13", features = ["tokio"] }
rlimit = "0.10.1"
passfd = { version = "*" }
which = "8.0.0"

# daemonize-me = "2.0.1"
