use alacritty_terminal::event::{Event, EventListener};
use alacritty_terminal::grid::Scroll;
use alacritty_terminal::term::cell;
use alacritty_terminal::term::TermMode;
use alacritty_terminal::term::{self, test::TermSize, Term};
use alacritty_terminal::vte::ansi::{Color, NamedColor, Processor};
use egui::epaint::RectShape;
use egui::{Align2, Color32, CornerRadius, FontId, Key, Painter, Pos2, Rect, Response, Shape, Vec2, Widget};
use std::sync::{Arc, Mutex};

/// Event listener that captures PtyWrite responses (device attribute replies,
/// color queries, etc.) so they can be sent back to the PTY.
#[derive(Clone, Debug, Default)]
pub struct PtyWriteCollector {
    pending: Arc<Mutex<Vec<Vec<u8>>>>,
}

impl EventListener for PtyWriteCollector {
    fn send_event(&self, event: Event) {
        if let Event::PtyWrite(text) = event {
            if let Ok(mut guard) = self.pending.lock() {
                guard.push(text.into_bytes());
            }
        }
    }
}

pub struct TermSession {
    term: Term<PtyWriteCollector>,
    processor: Processor,
    event_collector: PtyWriteCollector,
    pub pid: u32,
    pub last_size: (u16, u16),
}

impl TermSession {
    pub fn new(pid: u32) -> Self {
        let size = TermSize::new(120, 50);
        let event_collector = PtyWriteCollector::default();
        let term = Term::new(term::Config::default(), &size, event_collector.clone());
        Self {
            term,
            processor: Processor::new(),
            event_collector,
            pid,
            last_size: (120, 50),
        }
    }

    pub fn feed(&mut self, data: &[u8]) {
        self.processor.advance(&mut self.term, data);
    }

    /// Drain any PtyWrite responses generated by alacritty_terminal
    /// (e.g. device attribute replies). These must be sent back to the PTY.
    pub fn drain_responses(&mut self) -> Vec<Vec<u8>> {
        self.event_collector
            .pending
            .lock()
            .map(|mut v| std::mem::take(&mut *v))
            .unwrap_or_default()
    }

    pub fn resize(&mut self, cols: u16, rows: u16) {
        let cols = cols.max(2);
        let rows = rows.max(2);
        self.last_size = (cols, rows);
        self.term.resize(TermSize::new(cols as usize, rows as usize));
    }

    pub fn scroll(&mut self, delta: i32) {
        let mode = *self.term.mode();
        if mode.contains(TermMode::ALTERNATE_SCROLL | TermMode::ALT_SCREEN) {
            return;
        }
        self.term.grid_mut().scroll_display(Scroll::Delta(delta));
    }
}

pub struct TermView<'a> {
    session: &'a mut TermSession,
    has_focus: bool,
    size: Vec2,
    input_sink: &'a mut Vec<Vec<u8>>,
    resize_sink: &'a mut Option<(u16, u16)>,
}

impl<'a> TermView<'a> {
    pub fn new(
        session: &'a mut TermSession,
        input_sink: &'a mut Vec<Vec<u8>>,
        resize_sink: &'a mut Option<(u16, u16)>,
    ) -> Self {
        Self {
            session,
            has_focus: true,
            size: Vec2::ZERO,
            input_sink,
            resize_sink,
        }
    }

    pub fn set_focus(mut self, has_focus: bool) -> Self {
        self.has_focus = has_focus;
        self
    }

    pub fn set_size(mut self, size: Vec2) -> Self {
        self.size = size;
        self
    }

    fn process_input(&mut self, layout: &Response) {
        if !layout.has_focus() {
            return;
        }

        let is_app_cursor = self.session.term.mode().contains(TermMode::APP_CURSOR);

        let events = layout.ctx.input(|i| i.events.clone());
        for event in events {
            match event {
                // egui converts Ctrl+C into Copy, not a Key event.
                egui::Event::Copy => {
                    self.input_sink.push(vec![0x03]);
                }
                egui::Event::Cut => {
                    self.input_sink.push(vec![0x03]);
                }
                egui::Event::Text(text) => {
                    if !text.chars().any(char::is_control) {
                        self.input_sink.push(text.into_bytes());
                    }
                }
                egui::Event::Paste(text) => {
                    self.input_sink.push(text.into_bytes());
                }
                egui::Event::Key {
                    key,
                    pressed,
                    modifiers,
                    ..
                } if pressed => {
                    if modifiers.ctrl && key == Key::C {
                        self.input_sink.push(vec![0x03]);
                        continue;
                    }
                    if modifiers.ctrl && key == Key::D {
                        self.input_sink.push(vec![0x04]);
                        continue;
                    }
                    if modifiers.ctrl && key == Key::L {
                        self.input_sink.push(vec![0x0c]);
                        continue;
                    }
                    let bytes = match key {
                        Key::Backspace if modifiers.ctrl => Some(vec![0x17]),
                        Key::Enter => Some(vec![b'\r']),
                        Key::Backspace => Some(vec![0x7f]),
                        Key::Tab => Some(vec![b'\t']),
                        Key::Escape => Some(vec![0x1b]),
                        Key::ArrowUp if is_app_cursor => Some(b"\x1bOA".to_vec()),
                        Key::ArrowDown if is_app_cursor => Some(b"\x1bOB".to_vec()),
                        Key::ArrowRight if is_app_cursor => Some(b"\x1bOC".to_vec()),
                        Key::ArrowLeft if is_app_cursor => Some(b"\x1bOD".to_vec()),
                        Key::ArrowUp => Some(b"\x1b[A".to_vec()),
                        Key::ArrowDown => Some(b"\x1b[B".to_vec()),
                        Key::ArrowRight => Some(b"\x1b[C".to_vec()),
                        Key::ArrowLeft => Some(b"\x1b[D".to_vec()),
                        Key::Home if is_app_cursor => Some(b"\x1bOH".to_vec()),
                        Key::End if is_app_cursor => Some(b"\x1bOF".to_vec()),
                        Key::Home => Some(b"\x1b[H".to_vec()),
                        Key::End => Some(b"\x1b[F".to_vec()),
                        Key::Delete => Some(b"\x1b[3~".to_vec()),
                        Key::PageUp => Some(b"\x1b[5~".to_vec()),
                        Key::PageDown => Some(b"\x1b[6~".to_vec()),
                        _ => None,
                    };
                    if let Some(bytes) = bytes {
                        self.input_sink.push(bytes);
                    }
                }
                egui::Event::MouseWheel { unit, delta, .. } => {
                    let lines = match unit {
                        egui::MouseWheelUnit::Line => {
                            delta.y.signum() as i32 * (delta.y.abs().ceil() as i32) * 3
                        }
                        egui::MouseWheelUnit::Point => {
                            let font_size = 14.0_f32;
                            let l = (delta.y / font_size * 3.0).round() as i32;
                            if l != 0 { l } else { continue; }
                        }
                        egui::MouseWheelUnit::Page => continue,
                    };
                    self.session.scroll(lines);
                }
                _ => {}
            }
        }
    }

    fn font_measure(ctx: &egui::Context) -> (f32, f32) {
        let font_id = FontId::monospace(14.0);
        ctx.fonts_mut(|f| {
            (f.glyph_width(&font_id, 'm'), f.row_height(&font_id))
        })
    }

    fn maybe_resize(&mut self, layout: &Response) {
        let (cell_w, cell_h) = Self::font_measure(&layout.ctx);
        let cols = (layout.rect.width() / cell_w).floor().max(2.0) as u16;
        let rows = (layout.rect.height() / cell_h).floor().max(2.0) as u16;
        if self.session.last_size != (cols, rows) {
            self.session.resize(cols, rows);
            *self.resize_sink = Some((cols, rows));
        }
    }

    fn show(&mut self, layout: &Response, painter: &Painter) {
        let bg = Color32::from_rgb(10, 12, 16);
        let font_id = FontId::monospace(14.0);
        let (cell_w, cell_h) = Self::font_measure(&layout.ctx);
        let mut shapes = vec![Shape::Rect(RectShape::filled(
            Rect::from_min_max(layout.rect.min, layout.rect.max),
            CornerRadius::ZERO,
            bg,
        ))];

        let grid = self.session.term.grid();
        let cursor = grid.cursor.clone();
        let display_offset = grid.display_offset() as i32;

        for indexed in grid.display_iter() {
            if indexed.cell.flags.contains(cell::Flags::WIDE_CHAR_SPACER) {
                continue;
            }

            let point = indexed.point;
            let x = layout.rect.min.x + (cell_w * point.column.0 as f32);
            let y = layout.rect.min.y + (cell_h * (point.line.0 + display_offset) as f32);
            let mut fg = color_to_egui(indexed.fg, Color32::LIGHT_GRAY);
            let mut bg = color_to_egui(indexed.bg, bg);

            if indexed.cell.flags.contains(cell::Flags::INVERSE) {
                std::mem::swap(&mut fg, &mut bg);
            }

            if bg != Color32::from_rgba_unmultiplied(0, 0, 0, 0) && bg != Color32::from_rgb(10, 12, 16) {
                shapes.push(Shape::Rect(RectShape::filled(
                    Rect::from_min_size(Pos2::new(x, y), Vec2::new(cell_w + 1.0, cell_h + 1.0)),
                    CornerRadius::ZERO,
                    bg,
                )));
            }

            if cursor.point == point {
                shapes.push(Shape::Rect(RectShape::filled(
                    Rect::from_min_size(Pos2::new(x, y), Vec2::new(cell_w, cell_h)),
                    CornerRadius::ZERO,
                    Color32::from_rgb(220, 220, 220),
                )));
                fg = Color32::from_rgb(20, 20, 20);
            }

            if indexed.c != ' ' && indexed.c != '\t' {
                shapes.push(painter.fonts_mut(|fonts| {
                    Shape::text(
                        fonts,
                        Pos2::new(x + (cell_w / 2.0), y),
                        Align2::CENTER_TOP,
                        indexed.c,
                        font_id.clone(),
                        fg,
                    )
                }));
            }
        }

        painter.extend(shapes);
    }
}

impl Widget for TermView<'_> {
    fn ui(mut self, ui: &mut egui::Ui) -> Response {
        let size = if self.size == Vec2::ZERO {
            ui.available_size()
        } else {
            self.size
        };
        let (layout, painter) = ui.allocate_painter(size, egui::Sense::click_and_drag());

        if layout.clicked() {
            layout.request_focus();
        }

        // While focused, prevent egui from using Tab/arrows for widget navigation.
        if layout.has_focus() {
            let id = layout.id;
            ui.memory_mut(|mem| mem.set_focus_lock_filter(id, egui::EventFilter {
                tab: true,
                horizontal_arrows: true,
                vertical_arrows: true,
                escape: false,
            }));
        }

        self.maybe_resize(&layout);
        self.process_input(&layout);
        self.show(&layout, &painter);
        layout
    }
}

fn color_to_egui(color: Color, default: Color32) -> Color32 {
    match color {
        Color::Spec(rgb) => Color32::from_rgb(rgb.r, rgb.g, rgb.b),
        Color::Named(named) => named_to_color(named).unwrap_or(default),
        _ => default,
    }
}

fn named_to_color(color: NamedColor) -> Option<Color32> {
    let c = match color {
        NamedColor::Foreground => Color32::from_rgb(220, 220, 220),
        NamedColor::Background => Color32::from_rgb(10, 12, 16),
        NamedColor::Black => Color32::from_rgb(20, 20, 20),
        NamedColor::Red => Color32::from_rgb(220, 90, 90),
        NamedColor::Green => Color32::from_rgb(110, 200, 120),
        NamedColor::Yellow => Color32::from_rgb(220, 190, 90),
        NamedColor::Blue => Color32::from_rgb(120, 170, 240),
        NamedColor::Magenta => Color32::from_rgb(190, 130, 220),
        NamedColor::Cyan => Color32::from_rgb(100, 200, 210),
        NamedColor::White => Color32::from_rgb(220, 220, 220),
        _ => return None,
    };
    Some(c)
}
