use alacritty_terminal::event::{Event, EventListener};
use alacritty_terminal::grid::Scroll;
use alacritty_terminal::term::cell;
use alacritty_terminal::term::{TermDamage, TermMode};
use alacritty_terminal::term::{self, test::TermSize, Term};
use alacritty_terminal::vte::ansi::{Color, NamedColor, Processor};
use egui::epaint::{Galley, RectShape};
use egui::{Align2, Color32, CornerRadius, FontId, Key, Painter, Pos2, Rect, Response, Shape, Vec2, Widget};
use smallstr::SmallString;
use std::collections::HashMap;
use std::sync::Arc;

/// Compact string type: runs up to 32 bytes fit inline (no heap alloc).
/// Most terminal text runs on a single row are well under 120 single-byte chars
/// but we limit the inline size to 32 — longer runs promote to heap.
type S = SmallString<[u8; 32]>;

/// Per-viewport-row cached render data.
/// Positions are stored in grid-space (col index) so they remain valid
/// across window moves; pixel coords are computed cheaply at emit time.
#[derive(Clone)]
struct CachedRow {
    /// Background fill rects: (col, width_in_cells, color)
    bg_rects: Vec<(usize, f32, Color32)>,
    /// Text runs: (col, pre-shaped galley)
    text_runs: Vec<(usize, Arc<Galley>)>,
}

/// Event listener that captures PtyWrite responses (device attribute replies,
/// color queries, etc.) so they can be sent back to the PTY.
///
/// Uses a `flume` channel — no Mutex contention between the alacritty
/// event callback (sender) and the drain path (receiver sit in TermSession).
#[derive(Clone, Debug)]
pub struct PtyWriteCollector {
    tx: flume::Sender<Vec<u8>>,
}

impl EventListener for PtyWriteCollector {
    fn send_event(&self, event: Event) {
        if let Event::PtyWrite(text) = event {
            let _ = self.tx.try_send(text.into_bytes());
        }
    }
}

pub struct TermSession {
    term: Term<PtyWriteCollector>,
    processor: Processor,
    write_rx: flume::Receiver<Vec<u8>>,
    pub pid: u32,
    pub last_size: (u16, u16),

    /// Galley cache: (text_run_content, color) → Arc<Galley>.
    ///
    /// Key uses SmallString<[u8;32]> to avoid heap allocation for short runs.
    /// Built once via `fonts_mut` on first encounter; reused via `Shape::galley`
    /// on subsequent frames with zero font-lock overhead.
    galley_cache: HashMap<(S, Color32), Arc<Galley>>,

    /// Per-viewport-row render cache, indexed 0..num_rows.
    /// `None` means the row is dirty and must be rebuilt before use.
    row_cache: Vec<Option<CachedRow>>,

    /// Set when the entire row cache needs an unconditional rebuild
    /// (e.g. after a scroll that shifts which grid lines are on screen).
    force_full_rebuild: bool,

    /// Cached (cell_w, cell_h) from a single fonts_mut call.
    /// The font is fixed (monospace 14pt) so this never changes at runtime;
    /// we measure it once on first frame and reuse forever.
    cached_cell_dims: Option<(f32, f32)>,

    /// Pre-allocated per-row scratch buffer: indexed [0..num_rows].
    /// Each inner Vec accumulates (col, char, fg, bg, wide) for dirty rows.
    /// Cleared in-place each frame — no per-frame heap allocation.
    dirty_row_cells: Vec<Vec<(usize, char, Color32, Color32, bool)>>,
}

impl TermSession {
    pub fn new(pid: u32) -> Self {
        let size = TermSize::new(120, 50);
        let (tx, write_rx) = flume::unbounded();
        let event_collector = PtyWriteCollector { tx };
        let term = Term::new(term::Config::default(), &size, event_collector);
        let num_rows = 50usize;
        Self {
            term,
            processor: Processor::new(),
            write_rx,
            pid,
            last_size: (120, 50),
            galley_cache: HashMap::new(),
            row_cache: vec![None; num_rows],
            force_full_rebuild: true,
            cached_cell_dims: None,
            dirty_row_cells: (0..num_rows).map(|_| Vec::new()).collect(),
        }
    }

    pub fn feed(&mut self, data: &[u8]) {
        self.processor.advance(&mut self.term, data);
        // Do NOT call reset_damage here; damage is consumed in show().
    }

    /// Drain PtyWrite responses generated by alacritty_terminal
    /// (e.g. device attribute replies). These must be sent back to the PTY.
    pub fn drain_responses(&mut self) -> Vec<Vec<u8>> {
        self.write_rx.try_iter().collect()
    }

    pub fn resize(&mut self, cols: u16, rows: u16) {
        let cols = cols.max(2);
        let rows = rows.max(2);
        self.last_size = (cols, rows);
        self.term.resize(TermSize::new(cols as usize, rows as usize));
        // Resize invalidates all cached row positions and content.
        let r = rows as usize;
        self.row_cache.resize_with(r, || None);
        for slot in &mut self.row_cache {
            *slot = None;
        }
        self.dirty_row_cells.resize_with(r, Vec::new);
        // (dirty_row_cells inner vecs are cleared at the start of show(), no need here)
        self.force_full_rebuild = true;
    }

    pub fn scroll(&mut self, delta: i32) {
        let mode = *self.term.mode();
        if mode.contains(TermMode::ALTERNATE_SCROLL | TermMode::ALT_SCREEN) {
            return;
        }
        self.term.grid_mut().scroll_display(Scroll::Delta(delta));
        // Scroll shifts which grid lines are in the viewport — invalidate all rows.
        self.force_full_rebuild = true;
    }
}

pub struct TermView<'a> {
    session: &'a mut TermSession,
    has_focus: bool,
    size: Vec2,
    input_sink: &'a mut Vec<Vec<u8>>,
    resize_sink: &'a mut Option<(u16, u16)>,
}

impl<'a> TermView<'a> {
    pub fn new(
        session: &'a mut TermSession,
        input_sink: &'a mut Vec<Vec<u8>>,
        resize_sink: &'a mut Option<(u16, u16)>,
    ) -> Self {
        Self {
            session,
            has_focus: true,
            size: Vec2::ZERO,
            input_sink,
            resize_sink,
        }
    }

    pub fn set_focus(mut self, has_focus: bool) -> Self {
        self.has_focus = has_focus;
        self
    }

    pub fn set_size(mut self, size: Vec2) -> Self {
        self.size = size;
        self
    }

    fn process_input(&mut self, layout: &Response) {
        if !layout.has_focus() {
            return;
        }

        let is_app_cursor = self.session.term.mode().contains(TermMode::APP_CURSOR);

        let events = layout.ctx.input(|i| i.events.clone());

        // On some platforms (especially in a dedicated OS window / external viewport),
        // Ctrl+C is consumed by the compositor and arrives only as Event::Copy,
        // never as Event::Key{ctrl,C}. On others (inline panel) both arrive.
        // To avoid double-send we only treat Copy as ^C when there is no
        // Key{ctrl,C} already in the queue.
        let has_ctrl_c_key = events.iter().any(|e| {
            matches!(e, egui::Event::Key { key: Key::C, pressed: true, modifiers, .. }
                if modifiers.ctrl)
        });

        for event in &events {
            match event {
                egui::Event::Copy if !has_ctrl_c_key => {
                    self.input_sink.push(vec![0x03]);
                }
                // Cut → ^X is not standard terminal behaviour; ignore silently.
                egui::Event::Text(text) => {
                    if !text.chars().any(char::is_control) {
                        self.input_sink.push(text.as_bytes().to_vec());
                    }
                }
                egui::Event::Paste(text) => {
                    self.input_sink.push(text.as_bytes().to_vec());
                }
                egui::Event::Key {
                    key,
                    pressed: true,
                    modifiers,
                    ..  
                } => {
                    // Ctrl+letter sequences
                    if modifiers.ctrl {
                        let byte = match key {
                            Key::C => Some(0x03u8),
                            Key::D => Some(0x04),
                            Key::L => Some(0x0c),
                            Key::Z => Some(0x1a),
                            Key::A => Some(0x01),
                            Key::E => Some(0x05),
                            Key::U => Some(0x15),
                            Key::K => Some(0x0b),
                            Key::W => Some(0x17),
                            _ => None,
                        };
                        if let Some(b) = byte {
                            self.input_sink.push(vec![b]);
                            continue;
                        }
                    }
                    let bytes: &[u8] = match key {
                        Key::Backspace if modifiers.ctrl => &[0x17],
                        Key::Enter    => &[b'\r'],
                        Key::Backspace => &[0x7f],
                        Key::Tab      => &[b'\t'],
                        Key::Escape   => &[0x1b],
                        Key::ArrowUp    if is_app_cursor => b"\x1bOA",
                        Key::ArrowDown  if is_app_cursor => b"\x1bOB",
                        Key::ArrowRight if is_app_cursor => b"\x1bOC",
                        Key::ArrowLeft  if is_app_cursor => b"\x1bOD",
                        Key::ArrowUp    => b"\x1b[A",
                        Key::ArrowDown  => b"\x1b[B",
                        Key::ArrowRight => b"\x1b[C",
                        Key::ArrowLeft  => b"\x1b[D",
                        Key::Home if is_app_cursor => b"\x1bOH",
                        Key::End  if is_app_cursor => b"\x1bOF",
                        Key::Home  => b"\x1b[H",
                        Key::End   => b"\x1b[F",
                        Key::Delete   => b"\x1b[3~",
                        Key::PageUp   => b"\x1b[5~",
                        Key::PageDown => b"\x1b[6~",
                        Key::F1  => b"\x1bOP",
                        Key::F2  => b"\x1bOQ",
                        Key::F3  => b"\x1bOR",
                        Key::F4  => b"\x1bOS",
                        Key::F5  => b"\x1b[15~",
                        Key::F6  => b"\x1b[17~",
                        Key::F7  => b"\x1b[18~",
                        Key::F8  => b"\x1b[19~",
                        Key::F9  => b"\x1b[20~",
                        Key::F10 => b"\x1b[21~",
                        Key::F11 => b"\x1b[23~",
                        Key::F12 => b"\x1b[24~",
                        _ => &[],
                    };
                    if !bytes.is_empty() {
                        self.input_sink.push(bytes.to_vec());
                    }
                }
                egui::Event::MouseWheel { unit, delta, .. } => {
                    let lines = match unit {
                        egui::MouseWheelUnit::Line => {
                            delta.y.signum() as i32 * (delta.y.abs().ceil() as i32) * 3
                        }
                        egui::MouseWheelUnit::Point => {
                            let font_size = 14.0_f32;
                            (delta.y / font_size * 3.0).round() as i32
                        }
                        egui::MouseWheelUnit::Page => 0,
                    };
                    if lines != 0 {
                        self.session.scroll(lines);
                    }
                }
                _ => {}
            }
        }
    }

    fn font_measure(session: &mut TermSession, ctx: &egui::Context) -> (f32, f32) {
        if let Some(dims) = session.cached_cell_dims {
            return dims;
        }
        let font_id = FontId::monospace(14.0);
        let dims = ctx.fonts_mut(|f| {
            (f.glyph_width(&font_id, 'm'), f.row_height(&font_id))
        });
        session.cached_cell_dims = Some(dims);
        dims
    }

    fn maybe_resize(&mut self, layout: &Response, cell_dims: (f32, f32)) {
        let (cell_w, cell_h) = cell_dims;
        let cols = (layout.rect.width() / cell_w).floor().max(2.0) as u16;
        let rows = (layout.rect.height() / cell_h).floor().max(2.0) as u16;
        if self.session.last_size != (cols, rows) {
            self.session.resize(cols, rows);
            *self.resize_sink = Some((cols, rows));
        }
    }

    fn show(&mut self, layout: &Response, painter: &Painter, cell_dims: (f32, f32)) {
        let bg_default = Color32::from_rgb(10, 12, 16);
        let font_id = FontId::monospace(14.0);
        let (cell_w, cell_h) = cell_dims;
        let rect = layout.rect;

        // ── Step 1: apply alacritty damage tracking ──────────────────────────
        //
        // TermDamage tells us which viewport rows changed since the last
        // reset_damage() call. We mark those slots in row_cache as None so
        // they get rebuilt below. `force_full_rebuild` covers scroll/resize.
        let damage = self.session.term.damage();
        match damage {
            TermDamage::Full => {
                for slot in &mut self.session.row_cache {
                    *slot = None;
                }
            }
            TermDamage::Partial(iter) => {
                if self.session.force_full_rebuild {
                    for slot in &mut self.session.row_cache {
                        *slot = None;
                    }
                } else {
                    for bounds in iter {
                        if let Some(slot) = self.session.row_cache.get_mut(bounds.line) {
                            *slot = None;
                        }
                    }
                }
            }
        }
        self.session.term.reset_damage();
        self.session.force_full_rebuild = false;

        // ── Step 2: collect grid data ─────────────────────────────────────────
        let grid = self.session.term.grid();
        let cursor = grid.cursor.clone();
        let display_offset = grid.display_offset() as i32;
        let num_rows = self.session.last_size.1 as usize;

        // Clear pre-allocated scratch buffers in-place (no allocation).
        // Only rows whose cache slot is None (dirty) will be populated.
        for row in &mut self.session.dirty_row_cells {
            row.clear();
        }

        for indexed in grid.display_iter() {
            if indexed.cell.flags.contains(cell::Flags::WIDE_CHAR_SPACER) {
                continue;
            }
            let point = indexed.point;
            let vrow = (point.line.0 - display_offset) as usize;
            if vrow >= num_rows {
                continue;
            }
            // Only process if the slot needs rebuilding.
            if self.session.row_cache.get(vrow).map_or(true, |s| s.is_none()) {
                let mut fg = color_to_egui(indexed.fg, Color32::LIGHT_GRAY);
                let mut bg_cell = color_to_egui(indexed.bg, bg_default);
                if indexed.cell.flags.contains(cell::Flags::INVERSE) {
                    std::mem::swap(&mut fg, &mut bg_cell);
                }
                let wide = indexed.cell.flags.contains(cell::Flags::WIDE_CHAR);
                if let Some(row) = self.session.dirty_row_cells.get_mut(vrow) {
                    row.push((point.column.0, indexed.c, fg, bg_cell, wide));
                }
            }
        }

        // ── Step 3: rebuild dirty rows, using/populating the galley cache ─────
        //
        // galley_cache maps (text_content, color) → Arc<Galley>.
        // On a miss we call fonts_mut once (per unique text+color pair) to shape
        // the text. On subsequent frames the galley is reused with Shape::galley()
        // which needs NO font lock at all — just an Arc::clone().
        //
        // For a terminal with 256 colors × ~96 printable ASCII chars the cache
        // saturates after the first few seconds; steady-state fonts_mut calls ≈ 0.
        let galley_cache = &mut self.session.galley_cache;
        let row_cache = &mut self.session.row_cache;
        let dirty_row_cells = &self.session.dirty_row_cells;

        for (vrow, cells) in dirty_row_cells.iter().enumerate().filter(|(_, c)| !c.is_empty()) {
            let mut bg_rects: Vec<(usize, f32, Color32)> = Vec::new();

            // Build galley text runs: merge same-color consecutive chars.
            // SmallString avoids heap for runs ≤ 32 bytes (most terminal runs).
            struct Run {
                start_col: usize,
                text: S,
                color: Color32,
                next_col: usize,
            }
            let mut runs: Vec<Run> = Vec::new();
            let mut cur_run: Option<Run> = None;

            for &(col, c, fg, bg_cell, wide) in cells {
                let cell_w_ratio = if wide { 2.0f32 } else { 1.0 };

                if bg_cell != Color32::TRANSPARENT && bg_cell != bg_default {
                    bg_rects.push((col, cell_w_ratio, bg_cell));
                }

                if c == ' ' || c == '\t' || wide {
                    if let Some(run) = cur_run.take() {
                        runs.push(run);
                    }
                    if c != ' ' && c != '\t' {
                        // Wide char: solo run
                        let mut t = S::new();
                        t.push(c);
                        runs.push(Run { start_col: col, text: t, color: fg, next_col: col + 1 });
                    }
                } else {
                    let can_extend = cur_run
                        .as_ref()
                        .map_or(false, |r| r.color == fg && r.next_col == col);
                    if can_extend {
                        let r = cur_run.as_mut().unwrap();
                        r.text.push(c);
                        r.next_col = col + 1;
                    } else {
                        if let Some(run) = cur_run.take() {
                            runs.push(run);
                        }
                        let mut t = S::new();
                        t.push(c);
                        cur_run = Some(Run { start_col: col, text: t, color: fg, next_col: col + 1 });
                    }
                }
            }
            if let Some(run) = cur_run.take() {
                runs.push(run);
            }

            // Resolve galleys: cache hit → Arc clone (no font lock);
            //                  cache miss → fonts_mut (adds to atlas once).
            let mut text_runs: Vec<(usize, Arc<Galley>)> = Vec::with_capacity(runs.len());
            let mut needs_font: Vec<(usize, S, Color32)> = Vec::new();

            for run in &runs {
                let key = (run.text.clone(), run.color);
                if let Some(galley) = galley_cache.get(&key) {
                    text_runs.push((run.start_col, Arc::clone(galley)));
                } else {
                    needs_font.push((run.start_col, run.text.clone(), run.color));
                }
            }

            if !needs_font.is_empty() {
                // Single fonts_mut call per dirty row to shape all cache-miss runs.
                painter.ctx().fonts_mut(|fonts| {
                    for (col, text, color) in needs_font {
                        let galley = fonts.layout_no_wrap(text.to_string(), font_id.clone(), color);
                        galley_cache.insert((text, color), Arc::clone(&galley));
                        text_runs.push((col, galley));
                    }
                });
                // Re-sort by column (needs_font was appended after cache hits).
                text_runs.sort_unstable_by_key(|(col, _)| *col);
            }

            if let Some(slot) = row_cache.get_mut(vrow) {
                *slot = Some(CachedRow { bg_rects, text_runs });
            }
        }

        // ── Step 4: emit shapes from cache ───────────────────────────────────
        //
        // Pixel positions are computed here from current rect / display_offset.
        // This is pure arithmetic — no font or grid access.
        let mut shapes = vec![Shape::Rect(RectShape::filled(
            Rect::from_min_max(rect.min, rect.max),
            CornerRadius::ZERO,
            bg_default,
        ))];

        for (vrow, slot) in self.session.row_cache.iter().enumerate() {
            let Some(row) = slot else { continue };
            let y = rect.min.y + cell_h * vrow as f32;

            for &(col, width_ratio, color) in &row.bg_rects {
                let x = rect.min.x + cell_w * col as f32;
                shapes.push(Shape::Rect(RectShape::filled(
                    Rect::from_min_size(
                        Pos2::new(x, y),
                        Vec2::new(cell_w * width_ratio + 1.0, cell_h + 1.0),
                    ),
                    CornerRadius::ZERO,
                    color,
                )));
            }

            for (col, galley) in &row.text_runs {
                let x = rect.min.x + cell_w * (*col) as f32;
                // Shape::galley uses the pre-shaped Arc<Galley> directly —
                // zero font lock, just an Arc::clone internally.
                shapes.push(Shape::galley(Pos2::new(x, y), Arc::clone(galley), Color32::WHITE));
            }
        }

        // Cursor is drawn above the cached layer so it never invalidates row cache.
        let cvrow = (cursor.point.line.0 - display_offset) as usize;
        if cvrow < num_rows {
            let cx = rect.min.x + cell_w * cursor.point.column.0 as f32;
            let cy = rect.min.y + cell_h * cvrow as f32;
            shapes.push(Shape::Rect(RectShape::filled(
                Rect::from_min_size(Pos2::new(cx, cy), Vec2::new(cell_w, cell_h)),
                CornerRadius::ZERO,
                Color32::from_rgb(220, 220, 220),
            )));
        }

        painter.extend(shapes);
    }
}

impl Widget for TermView<'_> {
    fn ui(mut self, ui: &mut egui::Ui) -> Response {
        let size = if self.size == Vec2::ZERO {
            ui.available_size()
        } else {
            self.size
        };
        let (layout, painter) = ui.allocate_painter(size, egui::Sense::click_and_drag());

        if layout.clicked() {
            layout.request_focus();
        }

        // While focused, capture ALL navigation keys including Escape so egui
        // never steals focus. Escape defocusing the terminal caused the
        // "input hang" after pressing Esc or any key that triggered egui's
        // focus-navigation paths.
        if layout.has_focus() {
            let id = layout.id;
            ui.memory_mut(|mem| mem.set_focus_lock_filter(id, egui::EventFilter {
                tab: true,
                horizontal_arrows: true,
                vertical_arrows: true,
                escape: true,  // must be true: false causes Esc to defocus the terminal
            }));
        }

        // Measure font — hits cache after first frame (font is fixed, never changes).
        let cell_dims = Self::font_measure(self.session, &layout.ctx);
        self.maybe_resize(&layout, cell_dims);
        self.process_input(&layout);
        self.show(&layout, &painter, cell_dims);
        layout
    }
}

fn color_to_egui(color: Color, default: Color32) -> Color32 {
    match color {
        Color::Spec(rgb) => Color32::from_rgb(rgb.r, rgb.g, rgb.b),
        Color::Named(named) => named_to_color(named).unwrap_or(default),
        _ => default,
    }
}

fn named_to_color(color: NamedColor) -> Option<Color32> {
    let c = match color {
        NamedColor::Foreground => Color32::from_rgb(220, 220, 220),
        NamedColor::Background => Color32::from_rgb(10, 12, 16),
        NamedColor::Black => Color32::from_rgb(20, 20, 20),
        NamedColor::Red => Color32::from_rgb(220, 90, 90),
        NamedColor::Green => Color32::from_rgb(110, 200, 120),
        NamedColor::Yellow => Color32::from_rgb(220, 190, 90),
        NamedColor::Blue => Color32::from_rgb(120, 170, 240),
        NamedColor::Magenta => Color32::from_rgb(190, 130, 220),
        NamedColor::Cyan => Color32::from_rgb(100, 200, 210),
        NamedColor::White => Color32::from_rgb(220, 220, 220),
        _ => return None,
    };
    Some(c)
}
